version: '3.8'

services:
  flask-app:
    container_name: 'backend'
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - influxdb
    volumes:
      - ./data:/app/data

  influxdb:
    container_name: 'influxdb'
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
